app = "expensebot-app"
primary_region = "sin"

min_machines_running = 0

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"
  TZ = "Asia/Kolkata"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 8080

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    method = "get"
    path = "/"
    grace_period = "30s"
