app = "expensebot-app"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"
  TZ = "Asia/Kolkata"

# -------------------------
# HTTP service for health check
# -------------------------
[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 8080

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    method = "get"
    path = "/"
    grace_period = "30s"
