services:
  - type: worker
    name: expensebot-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    region: oregon
    autoDeploy: true

envVars:
  - key: BOT_TOKEN
    sync: false
  - key: SPREADSHEET_ID
    sync: false
  - key: GOOGLE_SA_KEY_B64
    sync: false
